name: DeltaEssentials
main: com.gmail.tracebachi.DeltaEssentials.Spigot.DeltaEssentialsPlugin
version: 3.1.0
author: GeeItsZee (tracebachi@gmail.com)
authors: [GeeItsZee (tracebachi@gmail.com), HotLava03 (tierriff@hotmail.com)]
depend: [SockExchange]
softdepend: [Vault, PermissionsEx]
api-version: '1.13'
commands:
  reply:
    aliases: [r]
  socialspy:
    aliases: [spy]
  tell:
    aliases: [t, m, msg, pm]
  playerfile:
    aliases: []
  blocktp:
    aliases: []
  tpaccept:
    aliases: []
  tpahere:
    aliases: []
  tp:
    aliases: []
  tpa:
    aliases: []
  tpdeny:
    aliases: []
  tphere:
    aliases: []
  dvanish:
    aliases: []
  findplayer:
    aliases: [isonline]
  disposal:
    aliases: [trash]
